"""Convert the four Figma projector frames into runtime-free pixel data.

The generated module contains only palettes and palette indices. The website
reconstructs every visible pixel with Canvas ImageData and never loads the
source PNGs at runtime.
"""

from __future__ import annotations

import base64
import json
from collections import deque
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets" / "about"
OUTPUT = ROOT / "about" / "about-device-pixel-data.js"
WIDTH = 400
HEIGHT = 399
COLORS = 256
EXTERIOR_LUMINANCE = 180
EXTERIOR_CHANNEL_SPREAD = 24


def resize_source(path: Path) -> Image.Image:
    with Image.open(path) as source:
        return source.convert("RGB").resize(
            (WIDTH, HEIGHT),
            Image.Resampling.LANCZOS,
        )


def encode_frame(path: Path) -> dict[str, object]:
    resized = resize_source(path)
    indexed = resized.quantize(
        colors=COLORS,
        method=Image.Quantize.MEDIANCUT,
        dither=Image.Dither.NONE,
    )

    raw_palette = indexed.getpalette() or []
    pixel_indices = indexed.get_flattened_data()
    used_colors = max(pixel_indices) + 1
    palette = []
    for index in range(used_colors):
        offset = index * 3
        red, green, blue = raw_palette[offset : offset + 3]
        palette.append((red << 16) | (green << 8) | blue)

    indices = bytes(pixel_indices)
    return {
        "palette": palette,
        "pixels": base64.b64encode(indices).decode("ascii"),
    }


def encode_opaque_mask(path: Path) -> str:
    """Remove only the light background connected to the canvas edges."""

    source = resize_source(path)
    pixels = source.load()
    exterior = bytearray(WIDTH * HEIGHT)
    queue: deque[tuple[int, int]] = deque()

    for x in range(WIDTH):
        queue.extend(((x, 0), (x, HEIGHT - 1)))
    for y in range(HEIGHT):
        queue.extend(((0, y), (WIDTH - 1, y)))

    while queue:
        x, y = queue.popleft()
        pixel_index = y * WIDTH + x
        if exterior[pixel_index]:
            continue

        red, green, blue = pixels[x, y]
        luminance = (red * 299 + green * 587 + blue * 114) // 1000
        channel_spread = max(red, green, blue) - min(red, green, blue)
        if (
            luminance < EXTERIOR_LUMINANCE
            or channel_spread > EXTERIOR_CHANNEL_SPREAD
        ):
            continue

        exterior[pixel_index] = 1
        if x > 0:
            queue.append((x - 1, y))
        if x + 1 < WIDTH:
            queue.append((x + 1, y))
        if y > 0:
            queue.append((x, y - 1))
        if y + 1 < HEIGHT:
            queue.append((x, y + 1))

    opaque_mask = bytearray((WIDTH * HEIGHT + 7) // 8)
    for pixel_index, is_exterior in enumerate(exterior):
        if not is_exterior:
            opaque_mask[pixel_index >> 3] |= 1 << (pixel_index & 7)

    return base64.b64encode(opaque_mask).decode("ascii")


def main() -> None:
    frames = [
        encode_frame(SOURCE_DIR / f"slide-{index}.png")
        for index in range(1, 5)
    ]
    payload = {
        "width": WIDTH,
        "height": HEIGHT,
        "opaqueMask": encode_opaque_mask(SOURCE_DIR / "slide-1.png"),
        "frames": frames,
    }
    module = (
        "// Generated by scripts/generate-about-pixel-data.py.\n"
        "// This module contains palette-indexed pixels, not encoded images.\n"
        f"export const ABOUT_DEVICE_PIXEL_DATA = {json.dumps(payload, separators=(',', ':'))};\n"
    )
    OUTPUT.write_text(module, encoding="utf-8")
    print(
        f"Wrote {OUTPUT.relative_to(ROOT)} "
        f"({OUTPUT.stat().st_size / 1024:.1f} KiB)"
    )


if __name__ == "__main__":
    main()
