"""Encode the four original About portraits as palette-indexed screen pixels.

The runtime reconstructs these pixels directly into Canvas ImageData. The
original JPEG files are build inputs only and are never loaded by the page.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets" / "about"
OUTPUT = ROOT / "about" / "about-photo-pixel-data.js"
WIDTH = 264
HEIGHT = 272
COLORS = 256

SOURCES = [
    ("photo-1.jpg", (0.60, 0.50)),
    ("photo-2.jpg", (0.50, 0.55)),
    ("photo-3.jpg", (0.50, 0.45)),
    ("photo-4.jpg", (0.50, 0.46)),
]


def encode_frame(filename: str, centering: tuple[float, float]) -> dict[str, object]:
    with Image.open(SOURCE_DIR / filename) as source:
        oriented = ImageOps.exif_transpose(source).convert("RGB")
        fitted = ImageOps.fit(
            oriented,
            (WIDTH, HEIGHT),
            method=Image.Resampling.LANCZOS,
            centering=centering,
        )

    indexed = fitted.quantize(
        colors=COLORS,
        method=Image.Quantize.MEDIANCUT,
        dither=Image.Dither.NONE,
    )
    raw_palette = indexed.getpalette() or []
    indices = bytes(indexed.get_flattened_data())
    used_colors = max(indices) + 1
    palette = []

    for index in range(used_colors):
        offset = index * 3
        red, green, blue = raw_palette[offset : offset + 3]
        palette.append((red << 16) | (green << 8) | blue)

    return {
        "palette": palette,
        "pixels": base64.b64encode(indices).decode("ascii"),
    }


def main() -> None:
    payload = {
        "width": WIDTH,
        "height": HEIGHT,
        "frames": [
            encode_frame(filename, centering)
            for filename, centering in SOURCES
        ],
    }
    module = (
        "// Generated by scripts/generate-about-photo-data.py.\n"
        "// Palette-indexed original photo pixels; no runtime image files are used.\n"
        f"export const ABOUT_PHOTO_PIXEL_DATA = {json.dumps(payload, separators=(',', ':'))};\n"
    )
    OUTPUT.write_text(module, encoding="utf-8")
    print(
        f"Wrote {OUTPUT.relative_to(ROOT)} "
        f"({OUTPUT.stat().st_size / 1024:.1f} KiB)"
    )


if __name__ == "__main__":
    main()
